- README.md
- log4js.json
- package.json
- src/Result.js
- src/Rule.js
- src/RuleSet.js
- src/SourceFile.js
- src/formatters/AnsiConsoleFormatter.js
- src/index.js
- src/rules/ResourceICUPlurals.js
- src/rules/ResourceQuoteStyle.js
- src/rules/ResourceUniqueKeys.js
- src/walk.js
- npm would not let me publish i18nlint because it is too close to another package's name (i18n-lint)
> Rename i18nlint -> ilib-lint

- src/FormatterManager.js
- src/ParserManager.js
- src/RuleManager.js
- src/index.js
- src/plugins/XliffParser.js
- src/rules/utils.js
- show all parsers, rules, rulesets, and formatters
- allows user to know what is available to add to their config
> Add the --list option to show all rules, etc.

- src/index.js
Print a summary of the total warnings and errors in a run before exiting the program.
> Make final output be total of errs and warnings

- README.md
- package.json
- forgot to do this in an earlier PR!
> Updated version # and README

- README.md
- package.json
- fixed packaging problem where the test plugin was listed in the dependencies instead of the devDependencies
> Fixed packaging problem

- README.md
- docs/resource-state-checker.md
- package.json
- src/rules/ResourceStateChecker.js
- test/testRules.js
- makes sure that the value of the state field of resources is either a particular value, or within an array of values
- default value is "translated"
> Added resource state checker which enforces resource states

- README.md
- package.json
- src/PluginManager.js
- I think it may have gotten deleted in all the merges
- need to publish this one right away as there are MANY resources with the wrong state
> Make sure the state checker rule can run

- README.md
- package.json
- we didn't update this section in the README properly before
> Enumerate all the plugins in the README

- README.md
- src/rules/ResourceQuoteStyle.js
- test/testResourceQuoteStyle.js
Don't emit error when quotes are missing in SV target
> Swedish quotes

- README.md
- jsconfig.json
- package.json
- src/FixerManager.js
- src/ParserManager.js
- src/PluginManager.js
- src/Project.js
- src/SourceFile.js
- src/formatters/AnsiConsoleFormatter.js
- src/formatters/ConfigBasedFormatter.js
- src/index.js
- test/ilib-lint-plugin-test/src/TestFixer.js
- test/ilib-lint-plugin-test/src/index.js
- test/testPluginManager.js
Requires https://github.com/iLib-js/i18nlint-common/pull/12
> Implement auto fix support

- README.md
- src/plugins/BuiltinPlugin.js
- src/rules/ResourceSourceICUPluralCategories.js
- src/rules/ResourceSourceICUPluralSyntax.js
- test/testPluginManager.js
- test/testResourceSourceICUPluralCategories.js
- test/testResourceSourceICUPluralSyntax.js
- test/testSuiteFiles.js
- rule that checks valid ICU plural syntax
- rule that checks categories in plural
> Implement rules for checking Source ICU plurals

- README.md
- package.json
- in preparation for making a new version
> Update the version number

- README.md
- package.json
- src/plugins/BuiltinPlugin.js
- test/testResourceNoDashesInReplacement.js
- test/testSuiteFiles.js
These are not allowed in ICU syntax.
> Check that replacement param names do not contain dashes

- docs/resource-no-escaped-curly-braces.md
- docs/source-no-escaped-curly-braces.md
- it was not clear before, and in some cases, just wrong
> Clarify the docs for quotes

- README.md
- package.json
- src/Project.js
- typo in import statement caused a problem
> Fixed bug in result sorting

- docs/resource-no-double-byte-space.md
- docs/resource-no-escaped-curly-braces.md
- docs/resource-no-fullwidth-digits.md
- docs/resource-no-fullwidth-latin.md
- docs/resource-no-fullwidth-punctuation-subset.md
- docs/resource-no-halfwidth-kana-characters.md
- docs/source-no-escaped-curly-braces.md
Added `<br>` in some doc files. If not, all sentence is displayed in one line.
> Add <br> in some doc files

- README.md
Fix to display the correct link in README
> Fix to display the correct link in README

- src/rules/ResourceQuoteStyle.js
Various fixes related to types in the quote style checking rule code
> Fix types in ResourceQuoteStyle

- docs/resource-no-fullwidth-punctuation-subset.md
- src/plugins/BuiltinPlugin.js
> Fix to content title to match filename

- docs/ReleaseNotes.md
- src/rules/ResourceQuoteStyle.js
- test/ResourceQuoteStyle.test.js
- but also accept square brackets as a type of quotes, even though it is not in CLDR
> Only accept the main quote style for Japanese

- src/plugins/BuiltinPlugin.js
- src/rules/ResourceICUPluralTranslation.js
- src/rules/ResourceICUPlurals.js
- src/rules/ResourceXML.js
- makes for better documentation when the links work properly!
> Quick fix: gihub.com -> github.com
