- README.md
- docs/resource-icu-plurals.md
- docs/resource-named-params.md
- docs/resource-quote-style.md
- docs/resource-unique-keys.md
- docs/resource-url-match.md
- package.json
- src/PluginManager.js
- src/formatters/AnsiConsoleFormatter.js
- src/formatters/ConfigBasedFormatter.js
- src/rules/ResourceICUPlurals.js
- src/rules/ResourceMatcher.js
- src/rules/ResourceQuoteStyle.js
- src/rules/ResourceSourceChecker.js
- src/rules/ResourceTargetChecker.js
- src/rules/ResourceUniqueKeys.js
- src/rules/SourceFileChecker.js
- test/testFormatterManager.js
- Rules can now have a link field which gives the URL to a web page that explains the rule in more detail and what to do about it if your code does not pass this rule
- Formatters can now output the link as well
- Declarative formatters now have a ruleLink field they can put in the template string
- Some md pages were created for the built-in rules and links to github were put in
> Add link field in Rules and Formatters

- docs/resource-no-fullwidth-digits.md
- docs/resource-no-fullwidth-latin.md
- src/PluginManager.js
- src/rules/ResourceMatcher.js
- src/rules/ResourceSourceChecker.js
- src/rules/ResourceTargetChecker.js
- test/testPluginManager.js
- test/testResourceTargetChecker.js
- test/testSuiteFiles.js
- needed to fix the previously-untested resource target and source checker type of rules
- make sure to add the "u" flag while creating the regexp so that we can specify unicode chars in the regexp
- actual check is implemented as a regular expression declarative rule in PluginManager.js
> Implement a check for fullwidth chars in the target

- README.md
- docs/resource-no-fullwidth-punctuation-subset.md
- package.json
- src/PluginManager.js
- test/testResourceTargetChecker.js
Added a regex declarative rule that detects if some specific fullwidth punctuation symbols were used in target: percent sign, question mark, or exclamation mark.
> Add rule to check for some fullwidth punctuations in resource target

- README.md
- package.json
- src/rules/ResourceICUPlurals.js
- test/testRules.js
- since it is a resource rule, it should only check the translation or that parts of the translation matches things in the source string.
- a source rule should be checking the source string separately
- this way, the source and resource rules can be turned on and off independently
> ICU Plural rule no longer checks the source string

- README.md
- docs/resource-completeness.md
- src/PluginManager.js
- src/rules/ResourceCompleteness.js
- test/testRules.js
Create a rule which ensures that in XLIFF files received from translation vendor, each trans-unit has both source and target elements defined.
TUs with missing target generate an error.
TUs with missing source (but existing target) generate a warning.
> Check if trans-unit is complete

- README.md
- src/rules/ResourceMatcher.js
- src/rules/ResourceSourceChecker.js
- src/rules/ResourceTargetChecker.js
- test/testResourceMatcher.js
- test/testResourceTargetChecker.js
- add unit tests for array and plural resources both positive and negative
- fix code to return the right results for resource matcher, resource source, and resource target types of declarative rules
> Fix checking of array and plural resources

- README.md
- docs/resource-dnt-terms.md
- src/PluginManager.js
- src/rules/ResourceDNTTerms.js
- test/testRules.js
- test/testfiles/dnt-test.json
- test/testfiles/dnt-test.txt
Create a rule that checks if the term exists in the source and if so, the same term appears somewhere in the target.
> Add rule to check Do Not Translate terms

- README.md
- docs/resource-no-halfwidth-kana-characters.md
- src/PluginManager.js
- test/testResourceTargetChecker.js
- New rule `resource-no-halfwidth-kana-characters` has been added.
- If target contains half-width kana character warning is returned. 
- Unit tests have been added.
> Add rule to check half-width kana characters

- src/rules/ResourceICUPluralTranslation.js
- test/testResourceICUPluralTranslation.js
- should check any added categories in the plural to see if they are the same as the "other" in English
- also make sure when there are subtracted categories in Asian languages, it does not crash
> Fix plural checker when there are added or subtracted categories

- README.md
- package.json
- src/rules/ResourceStateChecker.js
- test/testRules.js
- Having no state attribute on the target tag of a translation unit would cause an exception. Now it properly gives an error that no state was found.
> Fixed problem with checking transunit with no state

- README.md
- src/RuleManager.js
- src/SourceFile.js
- src/rules/DeclarativeResourceRule.js
- src/rules/LineRegexpChecker.js
- src/rules/ResourceCompleteness.js
- src/rules/ResourceDNTTerms.js
- src/rules/ResourceEdgeWhitespace.js
- src/rules/ResourceICUPluralTranslation.js
- src/rules/ResourceICUPlurals.js
- src/rules/ResourceMatcher.js
- src/rules/ResourceNoTranslation.js
- src/rules/ResourceQuoteStyle.js
- src/rules/ResourceRule.js
- src/rules/ResourceSourceChecker.js
- src/rules/ResourceTargetChecker.js
- test/testResourceICUPluralTranslation.js
- test/testResourceMatcher.js
- test/testResourceNoTranslation.js
- test/testResourceQuoteStyle.js
- test/testResourceTargetChecker.js
- test/testRules.js
- Added 2 new classes:
- DeclarativeResourceRule -> ResourceRule -> Rule
- ResourceRule implements match() where it handles iterating over the items in a resource array or the categories in a plural resource, calling matchString() on each of them
- this can be used for declarative or programmatic resource rules
- DeclarativeResourceRule implements matchString() and handles running a set of regular expressions on each string by calling checkString()
- The following all now inherit from ResourceRule and implement the matchString() method:
- ResourceEdgeWhitespace
- ResourceICUPlurals
- ResoruceICUPluralTranslation
- ResourceNoTranslation
- The following all now inherit from DeclarativeResourceRule and implement the checkString() method:
- ResourceMatcher
- ResourceSourceChecker
- …
> Refactored declarative and resource rules

- README.md
- package.json
- src/rules/ResourceICUPluralTranslation.js
- test/testResourceICUPluralTranslation.js
- it's okay for the source string of a plural category and the target string to be the same if the source string is empty!
> Don't produce a Result if source plural category is empty

- src/PluginManager.js
- src/plugins/BuiltinPlugin.js
- test/testResourceMatcher.js
- test/testResourceTargetChecker.js
- instead of initializing the built-in rules, rulesets, and formatters in the PluginManager, move the initialization into the BuiltinPlugin which is the more logical place for them to live
> Cleanup: move initialization to the builtin plugin

- README.md
- package.json
`intl-messageformat 10.4.0` update module settings have been changed - linter fails when trying to import it. This PR specifies direct linter dependency on this package version lesser than 10.4.
> Fix intl-messageformat dependency

- README.md
- package.json
- src/rules/ResourceICUPlurals.js
- test/testResourceICUPlurals.js
- rewrite the plural checker
- if the source has a syntax error, don't check the target (because we don't have something valid to check against!)
- now traverses the ast recursively, looking at nested selects/plurals at each level
- can deal with multiple independent or consecutive plurals at the same level
- finds the missing or extra plural categories in the target only. If the source is incorrect, errors are not reported. (It is up to the source checker to report on errors in the source.)
> Fix plural checker

- test/testResourceICUPlurals.js
When the source plural only has "=1" and "other", the linter should not complain when the target does not have a "one" category. This was fixed in the recent rewrite, but not fully tested. This PR adds unit tests to verify that it is indeed already working correctly.
> Add unit tests to show that linter is already working properly when there is a missing source category

- test/testResourceQuoteStyle.js
I thought the quote checker was not working properly because when you search in chrome for straight ASCII single quote, it matches the "extended" nine and six single quotes as well even though they are not the same character. However, when you use a different tool to look at the linter output that does not overmatch, it turns out that the xliffs were indeed not using the correct quotes and the linter output was accurate.
This PR adds a new unit test to verify that it is working properly for Dutch. No code change needed.
> Unit test to show Dutch quote checking is working properly

- README.md
- src/plugins/BuiltinPlugin.js
- test/testResourceTargetChecker.js
- super simple fix to make the rule that checks for spaces next to some ideographic punctuation characters only apply to Japanese. Specifically, it should not apply to Chinese.
- added a unit test to verify that it works correctly in Chinese
> Fix space next to ideo

- docs/source-no-lazy-plurals.md
- src/plugins/BuiltinPlugin.js
- test/testResourceNoLazyPlurals.js
- test/testSuiteFiles.js
- this is where the engineer or designer got lazy and put "(s)" at the end of the word to indicate that the number of items may be singular or plural instead of using actual plural syntax
> Add in rule to check for "lazy" plurals

- README.md
- docs/source-no-manual-percentage-formatting.md
- src/plugins/BuiltinPlugin.js
- test/testResourceNoManualPercentFormatting.js
- test/testSuiteFiles.js
- tell the engineer to use a locale-sensitive number formatter instead and substitute the result of that into this string
> Added new rule to check for manually formatted percentages

- README.md
- docs/source-no-noun-replacement-params.md
- package.json
- src/plugins/BuiltinPlugin.js
- test/testResourceNoNounReplacementParams.js
- test/testSuiteFiles.js
- if you use an article "a", "an", or "the" in front of a replacement parameter, this rule will give an error result because the article is untranslatable
> New rule to check for noun replacement params

- README.md
- docs/source-no-manual-currency-formatting.md
- src/plugins/BuiltinPlugin.js
- test/ResourceNoManualCurrencyFormatting.test.js
- currencies should be formatted with a locale-sensitive number formatter and given the currency code to use
> Add rule to check for manually formatted currency

- src/config/ConfigurationProvider.js
- test/ConfigurationProvider.test.js
Resolve absolute path to a JS config file before calling a dynamic import.
> Fix loading JS configs using relative paths

- README.md
- docs/resource-no-space-between-double-and-single-byte-character.md
- src/plugins/BuiltinPlugin.js
- test/ResourceTargetChecker.test.js
- fix the rule for Japanese that checks for no spaces between double- and single-byte character to allow a space between double-byte characters and single-byte punctuation characters
> Fix space rule to accept punctuation

- README.md
- package.json
- src/rules/ResourceQuoteStyle.js
- test/ResourceQuoteStyle.test.js
If the translation has a punctuation character next to the quote instead of a letter, then the quote style rule will trigger erroneously. Example:
Source:
> Showing {maxAmount} entries, "{sourceName}" has more.
Target:
> Affichant {maxAmount} entrées, « {sourceName} » en contient davantage.
This should not produce an error.
> Fix incorrect error about quote style when there is a bracket next to the quotes

- src/Project.js
Currently, if errorsOnly option is passed, a non-zero exit status is returned if there are warnings.
With this change, errorsOnly will only return non-zero if errors > 0
> Exit code should be 0 when warnings > 0 and errorsOnly option is true

- ReleaseNotes.md
- src/rules/ResourceSourceICUPluralCategories.js
- test/ResourceSourceICUPluralCategories.test.js
- now extra categories in the source are okay
- if the "=1" category exists and the "one" does not, then complain
> Fix the plural category checks

- .project
- src/FileType.js
- src/RuleSet.js
- test/FileType.test.js
- test/RuleSet.test.js
- fixed a bug where if you defined a ruleset that explicitly turned off a rule that was turned on by another ruleset, then it would never override it and turn off the rule. You would end up with a superset of all rules from all rule sets
> Fix rule type definitions

- README.md
- ReleaseNotes.md
- package.json
- src/FileType.js
- src/ParserManager.js
- src/Project.js
- src/SourceFile.js
- src/config/README.md
- test/Project.test.js
- test/SourceFile.test.js
- test/ilib-lint-plugin-test/package.json
- test/ilib-lint-plugin-test/src/TestParser.js
- test/testfiles/strings.pdq
- allows you to specify which parsers to use with the file type in the case where the file type uses some odd file name extension that the parsers don't recognize
- moved configuration processing from the Project constructor to the init method because we have to be able to load plugins first before we can process the configuration. The config may reference some of the parsers, rulesets, etc. that the plugins provide.
- updated some documentation
- cleaned some unnecessary stuff from the package.json
- added the ability for the parser manager to retrieve parsers by their name instead of only by file name extension
- now catches exceptions produced by the parsers for any given file, and only throws an error if ALL of the parsers fail to parse that file.
> Specify parsers in the file type

- README.md
- ReleaseNotes.md
- docs/resource-icu-plurals-translated.md
- docs/source-no-dashes-in-replacement-params.md
- docs/source-no-lazy-plurals.md
- docs/source-no-manual-currency-formatting.md
- docs/source-no-manual-date-formatting.md
- docs/source-no-manual-percentage-formatting.md
- docs/source-no-noun-replacement-params.md
- add documentation for rules resource-icu-plurals-translated and source-no-dashes-in-replacement-params
- added rule summaries in the README
- fixed some inaccuracies
> Add missing rule documentation

- docs/ReleaseNotes.md
- package.json
- src/PluginManager.js
- test/PluginManager.test.js
- test/plugin-test/package.json
- test/plugin-test/src/index.js
- fixed loading of plugins
- if a plugin `ilib-lint-x` exists and a different package `x`
also exists that is unrelated to ilib-lint, and the config
says to load the plugin named simply `x`, it would first attempt
to load package `x`, succeed to load it, but then fail to
initialize it because `x` is not really an ilib-lint plugin.
- Another problem is that if this type of error occurred, it
would not attempt to load any other paths or plugins. This means
it would not load the perfectly valid plugin that is there
just because there was a conflicting package name.
- Additionally, if given a path directly to the plugin (absolute
or relative), it would not load that specific plugin and just
fail completely.
- Now, it:
- loads the specific plugin given a path to it
- if the plugin name is …
> Fix the way that plugins are loaded

- docs/ReleaseNotes.md
- package.json
- src/rules/ResourceQuoteStyle.js
- test/ResourceQuoteStyle.test.js
fixed a bug where the quote style checker was not converting the highlight quotes properly
If not, the capturing $3 group is missing.
> fixed a bug where the quote style checker was not converting the highlight quotes properly

- docs/ReleaseNotes.md
- package.json
- src/index.js
- still prints out results, but always exits with return value 0.
- the intention is that we can use the linter in build pipelines to print out results, and yet not cause the build to fail
> Add the --no-return-value command-line flag

- docs/ReleaseNotes.md
- package.json
- src/LintableFile.js
- if there is only one parser for a file, show the actual parse error instead of a generic message that all parsers failed.
- updated dependencies
> Give better error messages when parsing fails

- docs/ReleaseNotes.md
- package.json
- src/plugins/BuiltinPlugin.js
- src/plugins/LineSerializer.js
- src/plugins/XliffParser.js
- src/plugins/XliffSerializer.js
- src/plugins/string/StringSerializer.js
- test/XliffParser.test.js
- test/XliffSerializer.test.js
- test/testfiles/xliff/bad.xliff
- In preparation for making changes to the linter to modify and write out xliff files.
- Added unit tests for the xliff parser so we can verify this functionality
- This PR will not pass the checks until ilib-lint-common v3.1.0 is published, but I have tested it with v3.1.0 locally and all unit tests pass.
> Implement XliffParser.write method
